// noinspection JSUnusedGlobalSymbols

import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '@styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mnopi site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://mnopi.com">mnopi!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/repos/deb">
            <a className={styles.card}>
              <h2>Repositories &rarr;</h2>
              <p>Debian packages.</p>
            </a>
          </Link>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://raw.githubusercontent.com/j5pu/sudoers/main/install"
            className={styles.card}
          >
            <h2>Sudoers &rarr;</h2>
            <p>Install and updates sudoers.d.</p>
          </a>

          <a
            href="/caca"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/mnopi.svg" alt="Mnopi Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
